### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by FaZoREX** [aclarembeau/go-mptcp-api#1]
Hello,

after running `	go get github.com/aclarembeau/go-mptcp-api` I get the following errors:

`# github.com/aclarembeau/go-mptcp-api
/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c: In function ‘mptcplib_open_sub’:

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:70:25: error: invalid application of ‘sizeof’ to incomplete type ‘struct mptcp_sub_tuple’
     int optlen = sizeof(struct mptcp_sub_tuple) + tuple->local_len + tuple->remote_len;
                         ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:73:14: error: dereferencing pointer to incomplete type ‘struct mptcp_sub_tuple’
     sub_tuple->id = 0;
              ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:83:49: error: ‘MPTCP_OPEN_SUB_TUPLE’ undeclared (first use in this function)
     int error = getsockopt(sockfd, IPPROTO_TCP, MPTCP_OPEN_SUB_TUPLE, sub_tuple, &optlen);
                                                 ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:83:49: note: each undeclared identifier is reported only once for each function it appears in
/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c: In function ‘mptcplib_get_sub_ids’:

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:108:45: error: ‘MPTCP_GET_SUB_IDS’ undeclared (first use in this function)
         r = getsockopt(sockfd, IPPROTO_TCP, MPTCP_GET_SUB_IDS, ids, &optlen);
                                             ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:115:44: error: dereferencing pointer to incomplete type ‘struct mptcp_sub_ids’
         struct mptcplib_intarray arr = {ids->sub_count, malloc(sizeof(int) * ids->sub_count)};
                                            ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c: In function ‘mptcplib_get_sub_tuple’:

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:139:14: error: dereferencing pointer to incomplete type ‘struct mptcp_sub_tuple’
     sub_tuple->id = id;
              ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:142:45: error: ‘MPTCP_GET_SUB_TUPLE’ undeclared (first use in this function)
     int r = getsockopt(sockfd, IPPROTO_TCP, MPTCP_GET_SUB_TUPLE, sub_tuple, &optlen);
                                             ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c: In function ‘mptcplib_close_sub’:
/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:197:31: error: storage size of ‘close_info’ isn’t known
     struct mptcp_close_sub_id close_info;
                               ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:199:34: error: invalid application of ‘sizeof’ to incomplete type ‘struct mptcp_close_sub_id’
     unsigned int optlen = sizeof(struct mptcp_close_sub_id);
                                  ^
/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:204:49: error: ‘MPTCP_CLOSE_SUB_ID’ undeclared (first use in this function)
     int error = getsockopt(sockfd, IPPROTO_TCP, MPTCP_CLOSE_SUB_ID, &close_info, &optlen);
                                                 ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c: In function ‘mptcplib_set_sub_sockopt’:
/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:213:33: error: storage size of ‘sub_sso’ isn’t known
     struct mptcp_sub_setsockopt sub_sso;
                                 ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:216:34: error: invalid application of ‘sizeof’ to incomplete type ‘struct mptcp_sub_setsockopt’
     unsigned int optlen = sizeof(struct mptcp_sub_setsockopt);
                                  ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:224:47: error: ‘MPTCP_SUB_SETSOCKOPT’ undeclared (first use in this function)
     int ret = setsockopt(sockfd, IPPROTO_TCP, MPTCP_SUB_SETSOCKOPT, &sub_sso, optlen);
                                               ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c: In function ‘mptcplib_get_sub_sockopt’:
/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:232:33: error: storage size of ‘sub_sso’ isn’t known
     struct mptcp_sub_getsockopt sub_sso;
                                 ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:236:34: error: invalid application of ‘sizeof’ to incomplete type ‘struct mptcp_sub_setsockopt’
     unsigned int optlen = sizeof(struct mptcp_sub_setsockopt);
                                  ^

/home/GO/src/github.com/aclarembeau/go-mptcp-api/mptcplib.c:244:49: error: ‘MPTCP_SUB_GETSOCKOPT’ undeclared (first use in this function)
     int error = getsockopt(sockfd, IPPROTO_TCP, MPTCP_SUB_GETSOCKOPT, &sub_sso, &optlen);
`

any help please

thanks

**Comment by aclarembeau** [comment]
Hello, 

You need to have the MPTCP socket API installed in your system. It will provide the structures: mptcp_sub_tuple and the different definitions such as : MPTCP_OPEN_SUB_TUPLE,  MPTCP_SUB_GETSOCKOPT, ... that are needed to compile the library (the purpose of this project is in fact to add a go layer to the native C structures that must be present). 

For instance, here is a link to a vagrant box with the library already installed: 
https://github.com/multipath-tcp/mptcp-vagrant

I hope it will help, 
Have a nice day, 

Alexis

**Comment by FaZoREX** [comment]
thank you very much for the reply. 
do I have to use the vagrant box to have the MPTCP socket API or is a way to directly install the socket API on a machine with MPTCP installed on it? any projects that has this socket API for direct installation?

Feri

**Comment by aclarembeau** [comment]
I think you will need to recompile the kernel in order to include the socket API (please anyone correct me if I am wrong). That is why I suggested using the vagrant box. 
However, if you want to build it directly from your machine, this fork from the MPTCP project contains a MPTCP enabled kernel with the socket API:  
https://github.com/hoang-tranviet/mptcp/tree/mptcp_v0.91_api_cleanup

Alexis

**Comment by FaZoREX** [comment]
thank you very much, I appreciate your kind help.

Feri
